# Generated by Django 5.2.1 on 2025-06-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_email_alter_myuser_match_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='match_password',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
