# Generated by Django 5.2.1 on 2025-06-07 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='ecommerce.product'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('product', 'attribute_key', 'attribute_value')},
        ),
    ]
